<a href="https://colab.research.google.com/github/adinsa1/Data110/blob/main/Lab_2_Solution(1)_(6).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1
import numpy as np
id_5 =np.identity(5)
id_5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
id_55 = np.eye(5)
id_55

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Q2
def reverse(x):
    y = x[::-1]
    return (y)

reverse(np.array([1,2,3,4]))


array([4, 3, 2, 1])

In [ ]:
#Q3
x = np.array([2, -5, -4, 1, 7, -9])
x[x<0] = 0
x

array([2, 0, 0, 1, 7, 0])

In [ ]:
#Q4
arr_34 = np.arange(12).reshape(3,4)
print(arr_34)
arr_34[:,[0,2]] = arr_34[:,[2,0]]
print(arr_34)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


In [ ]:
#Q5
rd = np.random.normal(loc=100, scale=15, size=(3,4))
rd

array([[ 95.56574664,  89.78462424, 100.58302024,  92.03817036],
       [ 93.65004206, 106.23794723,  95.95693713, 102.1030208 ],
       [ 94.39744113,  85.19988639, 121.40707168, 127.54683595]])