<a href="https://colab.research.google.com/github/adinsa1/Data110/blob/main/PandasTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
x=1
print(x)


1


In [3]:
# create pandas Series
s1=pd.Series()
s1

<ipython-input-3-758e5ef6e082>:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s1=pd.Series()


Series([], dtype: float64)

In [4]:
s2 = pd.Series([1,2,3,4,5])
s2


0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
# To get Index
s2.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
# to get values;
s2.values

array([1, 2, 3, 4, 5])

In [7]:
# to add defirent index
s3 = pd.Series([3.1,2.5,3.4,4.0,5.1], index=[10,20,30,40,50])
s3

10    3.1
20    2.5
30    3.4
40    4.0
50    5.1
dtype: float64

In [8]:
# to develop score of students by name
scores = pd.Series([1,2,3,4,5], index=['John', 'Sara', 'Emma', 'Ted','joe'])
scores

John    1
Sara    2
Emma    3
Ted     4
joe     5
dtype: int64

In [9]:
# find out index
scores.index

Index(['John', 'Sara', 'Emma', 'Ted', 'joe'], dtype='object')

In [10]:
# find out values
scores.values

array([1, 2, 3, 4, 5])

In [11]:
# Use Dictionary
d={'Bob':3.5, 'Joan': 4.3, 'Jack':35, 'Jake': 5.5}

s4 = pd.Series(d)
s4

Bob      3.5
Joan     4.3
Jack    35.0
Jake     5.5
dtype: float64

In [12]:
s4.index

Index(['Bob', 'Joan', 'Jack', 'Jake'], dtype='object')

In [13]:
s4.values

array([ 3.5,  4.3, 35. ,  5.5])

In [14]:
# DataFrame = data with several columns and rows: The result shows empty as there is value given

In [15]:
df1=pd.DataFrame()
type(df1)

pandas.core.frame.DataFrame

In [16]:
print(df1)

Empty DataFrame
Columns: []
Index: []


In [17]:
df1.columns

Index([], dtype='object')

In [18]:
df1.index

Index([], dtype='object')

In [19]:
df1.values

array([], shape=(0, 0), dtype=float64)

In [20]:
df1.shape

(0, 0)

In [21]:
## How to create DataFrame:
# first create nested list
students_list = [['Bob', 'Jake','Computer Engineering', 96],
               ['Ema', 'John', 'Math',78],
               ['Sara', 'Emy', 'Economics']]

In [22]:
students_df = pd.DataFrame(students_list)
students_df

0     1                     2     3
0   Bob  Jake  Computer Engineering  96.0
1   Ema  John                  Math  78.0
2  Sara   Emy             Economics   NaN

In [23]:
# How to specify Columns
students_df = pd.DataFrame(students_list, columns= ['First_Name', 'Last_Name', 'Major', 'Score'])
students_df

First_Name Last_Name                 Major  Score
0        Bob      Jake  Computer Engineering   96.0
1        Ema      John                  Math   78.0
2       Sara       Emy             Economics    NaN

In [24]:
# to change index to One,Two,Three
students_df = pd.DataFrame(students_list, columns= ['First_Name', 'Last_Name', 'Major', 'Score'],
                           index = ["One", "Two", "Three"])

students_df


First_Name Last_Name                 Major  Score
One          Bob      Jake  Computer Engineering   96.0
Two          Ema      John                  Math   78.0
Three       Sara       Emy             Economics    NaN

In [30]:
# Create DataFrame, above, using Dictionary instead:
students_dict = {'First_Name': ['Bob', 'Ema', 'Sara'],
               'Last_Name': ['Jake','John', 'Emy'],
               'Major': ['Computer Engineering', 'Math', 'Economics'],
               'Score': ['96', '78', '0'],}

students_df2 = pd.DataFrame(students_dict)
students_df2


First_Name Last_Name                 Major Score
0        Bob      Jake  Computer Engineering    96
1        Ema      John                  Math    78
2       Sara       Emy             Economics     0

In [33]:
# to retrieve Last Name and Score only:
students_df2 = pd.DataFrame(students_dict, columns=['Last_Name', 'Score'])
students_df2


Last_Name Score
0      Jake    96
1      John    78
2       Emy     0

In [35]:
# to get column information:
students_df.columns

Index(['First_Name', 'Last_Name', 'Major', 'Score'], dtype='object')

In [36]:
# to get index information:
students_df.index

Index(['One', 'Two', 'Three'], dtype='object')

In [37]:
# to get shape input:
students_df.shape

(3, 4)

In [39]:
students_df.head(2)

First_Name Last_Name                 Major  Score
One        Bob      Jake  Computer Engineering   96.0
Two        Ema      John                  Math   78.0

In [40]:
students_df.tail(2)

First_Name Last_Name      Major  Score
Two          Ema      John       Math   78.0
Three       Sara       Emy  Economics    NaN

In [41]:
students_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, One to Three
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   First_Name  3 non-null      object 
 1   Last_Name   3 non-null      object 
 2   Major       3 non-null      object 
 3   Score       2 non-null      float64
dtypes: float64(1), object(3)
memory usage: 228.0+ bytes


In [42]:
students_df.describe()

Score
count   2.000000
mean   87.000000
std    12.727922
min    78.000000
25%    82.500000
50%    87.000000
75%    91.500000
max    96.000000

# How To Read csv File

CSV Format

In [ ]:
## pd.read_csv()
pd.read_csv('datasets/data_01.csv')
df